DELETE FROM public.email_config WHERE tipo = 'convite_cliente';

INSERT INTO public.email_config (tipo, assunto, corpo_html, ativo, empresa_id)
VALUES (
  'convite_cliente',
  'Bem-vindo(a) à {{nome_empresa}}! 🎉',
  '<!DOCTYPE html><html lang="pt-br"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body style="margin: 0; padding: 0; background-color: #0a0a0a; font-family: ''Helvetica Neue'', Helvetica, Arial, sans-serif;"><center><div style="max-width: 600px; margin: 40px auto; background-color: #121212; border-radius: 24px; overflow: hidden; border: 1px solid #2a2a2a; box-shadow: 0 30px 60px rgba(0,0,0,0.8);"><div style="width: 100%; height: 200px; background-image: url(''https://10xmarketing.com.br/images/link-preview.jpg''); background-size: cover; background-position: center; position: relative;"><div style="position: absolute; inset: 0; background: linear-gradient(to bottom, transparent, #121212);"></div><div style="position: absolute; bottom: 15px; width: 100%; text-align: center;"><h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 800; letter-spacing: 2px; text-transform: uppercase;">{{nome_empresa}}</h1></div></div><div style="padding: 40px 30px; text-align: center;"><h2 style="color: #a855f7; font-size: 26px; margin-bottom: 10px; font-weight: 300;">Olá, <strong>{{nome_cliente}}</strong>! 👋</h2><p style="color: #a1a1aa; line-height: 1.8; font-size: 16px; margin-bottom: 30px;">Seja muito bem-vindo(a) ao seu novo ecossistema de marketing. Estamos felizes em tê-lo(a) como nosso(a) novo(a) assinante!</p><div style="background: rgba(168, 85, 247, 0.05); border-radius: 20px; padding: 30px; border: 1px solid rgba(168, 85, 247, 0.2);"><a href="{{link_login}}" style="display: block; padding: 16px 30px; background: linear-gradient(90deg, #9333ea, #7e22ce); color: #ffffff; text-decoration: none; border-radius: 12px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 15px; box-shadow: 0 10px 20px rgba(147, 51, 234, 0.3);">Acessar o Sistema</a><a href="{{link_definir_senha}}" style="display: block; padding: 14px 30px; background: transparent; color: #a855f7; text-decoration: none; border-radius: 12px; font-weight: bold; border: 2px solid #a855f7; text-transform: uppercase; letter-spacing: 1px;">Definir Minha Senha</a><p style="margin: 20px 0 0; color: #71717a; font-size: 13px;">Utilize os botões acima para configurar seu acesso e começar.</p></div><div style="margin-top: 30px; padding: 20px; border-top: 1px solid #2a2a2a;"><p style="margin: 0; color: #ffffff; font-size: 16px; font-weight: 600;">📱 Agendamento Facilitado</p><p style="margin: 8px 0 0; color: #64748b; font-size: 14px; line-height: 1.5;">Dentro da plataforma, você poderá agendar seus atendimentos e acompanhar o status dos seus serviços em tempo real.</p></div></div><div style="padding: 30px; background-color: #0a0a0a; text-align: center; border-top: 1px solid #1e1e1e;"><p style="color: #475569; font-size: 12px; margin: 0; letter-spacing: 1px;">{{nome_empresa}} - Estratégia e Escala<br>Obrigado pela preferência!</p></div></div></center></body></html>',
  true,
  NULL
);